### ISSUE TITLE
Cannot read properties of undefined (reading 'code')

### ISSUE THREAD

**Issue by ralyodio** [ajv-validator/ajv-formats#69]
```


Cannot read properties of undefined (reading 'code')

TypeError: Cannot read properties of undefined (reading 'code')
    at addFormats (/home/ettinger/src/avenasea.com/avenasea-ui/node_modules/ajv-formats/dist/index.js:30:26)
    at Proxy.formatsPlugin (/home/ettinger/src/avenasea.com/avenasea-ui/node_modules/ajv-formats/dist/index.js:15:5)
    at schema@blank.svelte:8:12
```

```
	import Ajv from 'ajv';
	import addFormats from 'ajv-formats';

	const ajv = new Ajv({ allErrors: true, strictSchema: false });
	addFormats(ajv);
```

**Comment by volnyansky** [comment]
@ralyodio faced the same issue. Found following workaround:
   `   const instance = new Ajv({code:{}});
    if (!instance.opts) {
        // @ts-ignore
        instance.opts = {code:{}};
    }
    const ajv = addFormats(instance,`
It looks like node platform issue, all works fine on macOs and crashes on linux.

**Comment by dipunm** [comment]
This doesn't work on my Mac: 
```
MacBook Pro (14-inch, 2021)
Chip: Apple M1 Pro
```

**Comment by cheburan** [comment]
The Same. Have these issues on my MacBook Pro (14-inch 2021), Chip: M1 Pro. Workaround helped
